[package]
name = "risp"
version = "0.1.0"
authors = ["Armando Herrera <self@geostran.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.3.0"
regex = "1.1.7"